### ISSUE TITLE
Disable users instead of delete

### ISSUE THREAD

**Issue by dust4sound** [zabbix-tooling/zabbix-ldap-sync#16]
Change/Add option to disable users instead of deleting them, so that the audit logs are kept.

**Comment by scoopex** [comment]
It seems that there is not option to disable a user.
https://www.zabbix.com/documentation/4.2/manual/api/reference/user/object

Depending on the auth mechanism it might be an option to rename a user or to change the password. Do you have ideas how to achieve this?

**Comment by dust4sound** [comment]
My thoughts on this would be to move them to the 'Disabled' group, and remove all other groups from the user.

**Comment by scoopex** [comment]
Seems to bee a good idea. Do you want to try to implement this?
Pull requests are very welcome :-)

Add a property named "disabled_group" - if its defined and the user was not part of the search results anymore, you can add the user to the name defined in that property.

**Comment by vryzhevsky** [comment]
Hi, I implemented this. See my Pull request

**Comment by scoopex** [comment]
Awesome! I will review and test this in the next days: https://github.com/zabbix-tooling/zabbix-ldap-sync/pull/33

**Comment by scoopex** [comment]
Implemented and merged. 
Many thanks @vryzhevsky! :-)
