### ISSUE TITLE
Other media types

### ISSUE THREAD

**Issue by towster** [zabbix-tooling/zabbix-ldap-sync#17]
This is sort of two issues.

I have set this up to sync from "mail" (AD) to "Email" (zabbix). This works fine.
I tried taking that working config and changing it to use "mobile" (AD) to "Pager" (zabbix custom script media type) but that fails. The error implies that the contents of "mobile" is not an email address - which it is not - it is a phone number.

If I manually add a phone number to Pager for one of the sync'd users and then run the original sync it wipes out the phone number of the user I manually added.

**Comment by towster** [comment]
So hacking at the code I managed to get first issue to work. The issue is within zabbixconn.py.

Line 115 in get_mediatype_id reads:
result = self.conn.mediatype.get(filter={'description': description})

I changed to:
result = self.conn.mediatype.get(filter={'name': description})

Before I did that I did try setting the description of the media types to match the names but it still always found the wrong one.

**Comment by towster** [comment]
Ok so that this may help someone else gonna paste this here. It is messy but it works. The second issue is because when you update a user you have to pass ALL of the media types for that user or it will remove any that you are not passing. I changed the code to pull the current media types that dont match the one we are changing and append that to the update. 

Here is what I changed in zabbixconn.py to fix the second issue:

```
    def update_media(self, user, description, sendto, media_opt):
        """
        Adds media to an existing Zabbix user

        Args:
            user        (dict): A dict containing the user details
            description  (str): A string containing Zabbix media description
            sendto       (str): A string containing address, phone number, etc...
            media_opt    (dict): Media options

        """

        userid = self.get_user_id(user)
        mediatypeid = self.get_mediatype_id(description)

        if mediatypeid:
            media_temp = {
                'mediatypeid': mediatypeid,
                'sendto': sendto,
                'active': '0',
                'severity': '63',
                'period': '1-7,00:00-24:00'
            }
            media_temp.update(media_opt)

            currmediatemp = self.conn.user.get(selectMedias=['mediatypeid','sendto','active','severity','period'],userids=userid,output='medias')
            self.logger.debug('update_media - currmediatemp %s' % (currmediatemp))

            currmedia = currmediatemp[0]['medias']
            self.logger.debug('update_media - currmedia %s' % (currmedia))
            media_defaults = [media_temp] 
            for m in currmedia:
                if m['mediatypeid'] != mediatypeid:
                   media_defaults.append(m)
            
            self.logger.debug('update_media - userid %s - mediatypeid %s - media_defaults %s' % (userid, mediatypeid, media_defaults))

            if self.conn.api_version() >= "3.4":
                result = self.conn.user.update(userid=str(userid), user_medias=media_defaults)
            else:
                self.delete_media_by_description(user, description)
                result = self.conn.user.updatemedia(users=[{"userid": str(userid)}], medias=media_defaults)
        else:
            result = None

        return result

```

**Comment by scoopex** [comment]
Thank you.
Can you send your contribution as a pull request?

**Comment by scoopex** [comment]
solved
