### ISSUE TITLE
Usage instructions for CentOS 8

### ISSUE THREAD

**Issue by samip5** [zabbix-tooling/zabbix-ldap-sync#20]
The recommended OS is CentOS for Zabbix and thus the instructions should be for it too.

What libraries do I need to install?

```
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -fPIC -fwrapv -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.3.1 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULE_LICENSE=Python style -IModules -I/home/sm/zabbix-ldap-sync/venv/include -I/usr/include/python3.6m -c Modules/LDAPObject.c -o build/temp.linux-x86_64-3.6/Modules/LDAPObject.o
    In file included from Modules/LDAPObject.c:3:
    Modules/common.h:15:10: fatal error: lber.h: No such file or directory
     #include <lber.h>
              ^~~~~~~~
    compilation terminated.
    error: command 'gcc' failed with exit status 1
```

**Comment by scoopex** [comment]
Sorry, i do not run Centos :-)
Ony my distrubtion lber.h resolvs to libldap2-dev.
```
$ locate lber.h
/usr/include/lber.h
$ dpkg -S /usr/include/lber.h
libldap2-dev:amd64: /usr/include/lber.h
```

Have a look at https://github.com/zabbix-tooling/zabbix-ldap-sync#requirements and https://github.com/zabbix-tooling/zabbix-ldap-sync#setup-virtualenv.

Probably you can contribute a list of packages to be installed for centos?
Opensource is not just getting software and support without paying - it's collaboration and freedom ;-)

**Comment by samip5** [comment]
> Sorry, i do not run Centos :-)
> Ony my distrubtion lber.h resolvs to libldap2-dev.
> 
> ```
> $ locate lber.h
> /usr/include/lber.h
> $ dpkg -S /usr/include/lber.h
> libldap2-dev:amd64: /usr/include/lber.h
> ```
> 
> Have a look at https://github.com/zabbix-tooling/zabbix-ldap-sync#requirements and https://github.com/zabbix-tooling/zabbix-ldap-sync#setup-virtualenv.
> 
> Probably you can contribute a list of packages to be installed for centos?
> Opensource is not just getting software and support without paying - it's collaboration and freedom ;-)

You're aware that the first thing I did, was to read the actual README?
Made a PR so it*s documented.
