### ISSUE TITLE
Typo in README | Severity attribute type

### ISSUE THREAD

**Issue by dariodsa** [zabbix-tooling/zabbix-ldap-sync#22]
### Current
```
[media]
description = Email
active = 0
period = 1-5,07:00-22:00
severity = Disaster, High, Average, Warning, Information, Not Classified
onlycreate = true
```

### Expected
```
[media]
description = Email
active = 0
period = 1-5,07:00-22:00
severity = 63
#Disaster, High, Average, Warning, Information, Not Classified
onlycreate = true
```

**Comment by scoopex** [comment]
Thanks for the PR. The value "Disaster, High, Average, Warning, Information, Not Classified" should be automatically converted to the numeric value. Does this not work for you?

**Comment by dariodsa** [comment]
No, it is working but then the documentation is wrong. 

```
severity = 63 - Decimal value of trigger severities to send notifications about. 
```

**Comment by scoopex** [comment]
Fixed by improving the documentation:
https://github.com/zabbix-tooling/zabbix-ldap-sync/commit/7935fc6e2a4075b1ae010ffd0988caab406464dc
