### ISSUE TITLE
Zabbix 5.2 replaced user property `type` with `roleid`.

### ISSUE THREAD

**Issue by Joshua-Snapp** [zabbix-tooling/zabbix-ldap-sync#24]
The zabbix-ldap-sync script fails when creating users with Zabbix 5.2 api.

The fix is to change `type` to `roleid` in the create_user function within [lib/zabbixconn.py](https://github.com/zabbix-tooling/zabbix-ldap-sync/blob/353a60f5fae1bb3b86faf870f3ffcccc6af6ce9e/lib/zabbixconn.py#L181) and in the user stanza of any configuration files. This change is ***not*** backwards compatible with Zabbix versions < 5.2.

-----------------
Here's more info about the change from `type` property to `roleid` in the user object:
>[USER](https://www.zabbix.com/documentation/current/manual/api/changes_5.0_-_5.2#user)
Changes:
[ZBXNEXT-6148](https://support.zabbix.com/browse/ZBXNEXT-6148) user.create, user.update, user.get: dropped support of type property.

>[USER](https://www.zabbix.com/documentation/current/manual/api/changes_5.0_-_5.2#user1)
Changes:
[ZBXNEXT-6148](https://support.zabbix.com/browse/ZBXNEXT-6148) user.create, user.update, user.get: added new property roleid.

User object - [5.2](https://www.zabbix.com/documentation/5.2/manual/api/reference/user/object) ([diff](https://www.zabbix.com/documentation/5.2/manual/api/reference/user/object?do=diff&rev2%5B0%5D=1603791177&rev2%5B1%5D=1604489220&difftype=sidebyside))

-----------------
Here's the traceback that occurs as soon as the script tries to create a user:
```
Traceback (most recent call last):
  File "/opt/zabbix-ldap-sync/zabbix-ldap-sync", line 112, in <module>
    main()
  File "/opt/zabbix-ldap-sync/zabbix-ldap-sync", line 109, in main
    zabbix_conn.sync_users()
  File "/opt/zabbix-ldap-sync/lib/zabbixconn.py", line 376, in sync_users
    self.create_user(user, zabbix_grpid, self.user_opt)
  File "/opt/zabbix-ldap-sync/lib/zabbixconn.py", line 185, in create_user
    result = self.conn.user.create(user)
  File "/opt/zabbix-ldap-sync/lib/python3.6/site-packages/pyzabbix/__init__.py", line 192, in fn
    args or kwargs
  File "/opt/zabbix-ldap-sync/lib/python3.6/site-packages/pyzabbix/__init__.py", line 169, in do_request
    raise ZabbixAPIException(msg, response_json['error']['code'], error=response_json['error'])
pyzabbix.ZabbixAPIException: ('Error -32602: Invalid params., Invalid parameter "/1": unexpected parameter "type".', -32602)
```

**Comment by scoopex** [comment]
Thanks for you contribution, i made it configurable now.
