### ISSUE TITLE
Not compatble with zabbix 5.2 user object dont have type

### ISSUE THREAD

**Issue by KivraChristoffer** [zabbix-tooling/zabbix-ldap-sync#27]
in zabbix 5.2 the user obj have changed and type have been removed.

**Comment by KivraChristoffer** [comment]
if self.conn.api_version() >= "5.2":
            user_defaults['roleid'] = 1
        else:
            user_defaults['type'] = 1
this seems not to be working as it should

**Comment by KivraChristoffer** [comment]
Found that i missed comment out a line in config.

**Comment by scoopex** [comment]
Thanks for the issue, i improved the documentation.
https://github.com/zabbix-tooling/zabbix-ldap-sync/commit/8de50bd23de7e63821c0484c86abe669e522e442
