### ISSUE TITLE
Error when script is attempting to remove the user.

### ISSUE THREAD

**Issue by huntastikus** [zabbix-tooling/zabbix-ldap-sync#29]
We are running the latest Zabbix version 5.2.6. I downloaded and installed the requirements, and I was able to import the users in the Active Directory group. However, when I removed a user and run the sync, I get the following error:
```
2021-04-15 15:00:52,276 - ZabbixConn - INFO - Connected to Zabbix API Version 5.2.6
2021-04-15 15:00:52,481 - ZabbixConn - INFO - Users in group Zabbix Super Admins which are not found in LDAP group:
2021-04-15 15:00:52,481 - ZabbixConn - INFO - User not in ldap group "werschmannj"
2021-04-15 15:00:52,482 - ZabbixConn - INFO - Update media on all users for group >>>Zabbix Super Admins<<<
2021-04-15 15:00:52,541 - ZabbixConn - INFO - >>> Updating/create user media for "muellervo", update "Email (HTML)"
2021-04-15 15:00:52,757 - ZabbixConn - INFO - >>> Updating/create user media for "hicklc", update "Email (HTML)"
2021-04-15 15:00:52,970 - ZabbixConn - INFO - >>> Updating/create user media for "werschmannj", update "Email (HTML)"
Traceback (most recent call last):
  File "./zabbix-ldap-sync", line 102, in <module>
    main()
  File "./zabbix-ldap-sync", line 98, in main
    zabbix_conn.sync_users()
  File "/root/zabbix-ldap-sync/lib/zabbixconn.py", line 436, in sync_users
    if self.ldap_conn.get_user_media(ldap_users[each_user], self.ldap_media):
KeyError: 'werschmannj'`
```

Is there a setting I missed somewhere?

**Comment by huntastikus** [comment]
We have tested with multiple users, same outcome.

**Comment by scoopex** [comment]
I will have a look at this issue at weekend.

**Comment by scoopex** [comment]
Implemented a bugfix. Please reopen if the problem is is existing and provide detailed logoutput, a redacted config an information about your ldap directory structure.

**Comment by huntastikus** [comment]
Hi, 
This project fell a little to the wayside, but now that we have some time to catch our breath, this is still an outstanding issue.
Here is our .conf file
`cat zabbix-ldap-superadmins.conf
[ldap]
type = activedirectory
uri = ldap://subdomain.domain.com:389/
base =DC=subdomain,DC=domain,DC=com
binduser = domain\domain.account
bindpass = Password
groups = Zabbix Super Admins
media = mail

[activedirectory]
filtergroup = (&(objectClass=group)(name=%s))
filteruser = (objectClass=user)(objectCategory=Person)
filterdisabled = (!(userAccountControl:1.2.840.113556.1.4.803:=2))
filtermemberof = (memberOf:1.2.840.113556.1.4.1941:=%s)
groupattribute = member
userattribute = sAMAccountName

[zabbix]
server = https://zabbix.subdomain.domain.com
username = zabbix.account
password = password
auth = webform

[user]
roleid = 3

[media]
description = Email (HTML)
active = 0
period = 1-5,07:00-22:00
severity = 56`

**Comment by scoopex** [comment]
Have you tried out my (guessed) implemented bugfix?
Regards Marc?

**Comment by huntastikus** [comment]
Yes I did, I just pulled a fresh copy of everything prior to testing, still resulted in the same issue. 
Also, I opened a new issue since I could not figure out how to "re-open" this. Shall I close that one?

**Comment by scoopex** [comment]
Reopened :-)

**Comment by jeremybusk** [comment]
Same issues. When deleted user out of group in ActiveDirectory and resync it errors out. This PR https://github.com/zabbix-tooling/zabbix-ldap-sync/pull/39 will at least allow it not to error out but not sure if I'm losing functionailty as I just started looking at sync options yesterday and saw this project.

**Comment by scoopex** [comment]
Please retry with the with the latest git release.
No update for months, unable to reproduce, please submit detailed debug and reopen.
