### ISSUE TITLE
KeyError message during sync on a particular user

### ISSUE THREAD

**Issue by mintegral** [zabbix-tooling/zabbix-ldap-sync#3]
Hello,

while running the script, I get an error message when the sync gets to a particular user:

> 2018-05-29 15:36:15,262 - INFO - >>> Updating/create user media for "user1", update "Email"
> 2018-05-29 15:36:15,262 - INFO - >>> Updating/create user media for "user1", update "Email"
> 2018-05-29 15:36:15,664 - INFO - Remove other exist media from user user2 (type=Email)
> 2018-05-29 15:36:15,664 - INFO - Remove other exist media from user user2 (type=Email)
> 2018-05-29 15:36:15,810 - INFO - >>> Updating/create user media for "user3", update "Email"
> 2018-05-29 15:36:15,810 - INFO - >>> Updating/create user media for "user3", update "Email"
> Traceback (most recent call last):
>   File "./zabbix-ldap-sync", line 92, in <module>
>     main()
>   File "./zabbix-ldap-sync", line 89, in main
>     zabbix_conn.sync_users()
>   File "/home/.../zabbix-ldap-sync-master/lib/zabbixconn.py", line 419, in sync_users
>     sendto = self.ldap_conn.get_user_media(ldap_users[eachUser], self.ldap_media).decode("utf8")
> KeyError: 'user3'

Can anybody help me?

**Comment by lroellin** [comment]
Does your user have an email address?

In my AD, some haven't. If that's the case, I have a config that works around this. However, no users have an email address then.

**Comment by craviee** [comment]
#6  can fix this issue.

**Comment by scoopex** [comment]
fixed with #6
