### ISSUE TITLE
alldirusergroup

### ISSUE THREAD

**Issue by athertonsp** [zabbix-tooling/zabbix-ldap-sync#34]
I was running your excellent script fine until just recently it complained (after an update): 

```
No option 'alldirusergroup' in section: 'zabbix'
Traceback (most recent call last):
  File "/usr/lib64/python3.6/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib64/python3.6/collections/__init__.py", line 883, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib64/python3.6/collections/__init__.py", line 875, in __missing__
    raise KeyError(key)
KeyError: 'alldirusergroup'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/zabbix-ldap-sync/lib/zabbixldapconf.py", line 75, in __init__
    self.zbx_alldirusergroup = parser.get('zabbix', 'alldirusergroup')
  File "/usr/lib64/python3.6/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'alldirusergroup' in section: 'zabbix'
Configuration issues detected in /data/.zbx-ldap-conf/CYC_Admins.cfg
```

Looking at the git, it seems a new parameter "alldirusergroup" has been added and is required, but I am not sure why it is there, why it is mandatory or indeed what it does. 
I created the required "catch all" group in my Zabbix implementation and of course it works but personally I would rather not have such a group; if I delete users I want them deleted for security purposes not lingering in an unusable Zabbix group - is it possible to give more explanation of this parameter and more importantly can it be bypassed\made optional?

Many thanks.

STEVE

**Comment by scoopex** [comment]
Oh, i am sorry for the inconvenience,
We already added some documentation about this:
(see https://github.com/zabbix-tooling/zabbix-ldap-sync/blob/master/README.md)
```
Group in Zabbix where to put all users created from the ldap directory.
Create this group before using this tool and give members of this group no permissions to your zabbix instance.
If a user is not available anymore by the directory, the user remains in this single group.
```

We added this feature because simply deleting users has the disadvantage that this chnages the zabbix audit trail.
I changed the code now to allow it not to use that functionality.
Can you provide feedback about that and if there are still things needed to be changed for your case?

**Comment by athertonsp** [comment]
Thank you Marc. 

Thank for the clarification. I had read the README but was not sure why it was needed. But in truth, changing the audit trail is actually an advantage for me.

We manage all our users from our RedHat Identity Manager LDAP instance, which itself also has an audit trail. When we delete users we have to a) make sure they are deleted and b) prove it to demonstrate security. So the audit trail is an advantage; having the users still exist in Zabbix is a disadvantage as we then have to manually delete them in Zabbix as well - which defeats the object of the LDAP synchronisation :) 

So I would like to have the option for it to work the way you had it before this change; either by an "off switch" to the command line parameters or something like "alldirusergroup=null" in the config file to allow us to optionally not use this feature?

Thanks for your help.

STEVE

**Comment by scoopex** [comment]
With the current implementation you should be capable to just delete the "alldirusergroup" attribute and to delete orphaned users with "--delete-orphans" /the old behavior).

**Comment by athertonsp** [comment]
Hi Marc - thanks for responding. I am not sure exactly what you mean - if I delete the "alldirusergroup" attribute from my config file, I get the error published at the top!  
Anyway - I have done testing and found that if I make the value of "alldirusergroup=" to be the same as the "groups=" attribute value in the LDAP section, I get around the creation of what to me was a superfluous Zabbix group. It was having two groups that was the problem but it seems I have worked around it. So many thanks but I now have a workable solution :)

**Comment by scoopex** [comment]
You should update your git-clone to use the improved implementation. :-)
