### ISSUE TITLE
Not able to delete users

### ISSUE THREAD

**Issue by huntastikus** [zabbix-tooling/zabbix-ldap-sync#36]
Hi,
This project fell a little to the wayside, but now that we have some time to catch our breath, this is still an outstanding issue.
Here is our .conf file
```
cat zabbix-ldap-superadmins.conf
[ldap]
type = activedirectory
uri = ldap://subdomain.domain.com:389/
base =DC=subdomain,DC=domain,DC=com
binduser = domain\domain.account
bindpass = Password
groups = Zabbix Super Admins
media = mail

[activedirectory]
filtergroup = (&(objectClass=group)(name=%s))
filteruser = (objectClass=user)(objectCategory=Person)
filterdisabled = (!(userAccountControl:1.2.840.113556.1.4.803:=2))
filtermemberof = (memberOf:1.2.840.113556.1.4.1941:=%s)
groupattribute = member
userattribute = sAMAccountName

[zabbix]
server = https://zabbix.subdomain.domain.com
username = zabbix.account
password = password
auth = webform

[user]
roleid = 3

[media]
description = Email (HTML)
active = 0
period = 1-5,07:00-22:00
severity = 56
```

**Comment by jeremybusk** [comment]
By delete users are you saying when you delete user out of group in AD it doesn't delete in Zabbix? I wasn't able to get that to work but I did have errors when empty AD groups that this PR fixes. Not great but something
https://github.com/zabbix-tooling/zabbix-ldap-sync/pull/39

**Comment by huntastikus** [comment]
That is exactly what I would like to do, delete users once they are no longer in the AD group.

**Comment by scoopex** [comment]
No update for months, unable to reproduce, please submit detailed debug information and reopen.
