### ISSUE TITLE
hardcoded .lower() for usernames in zabbixconn.py

### ISSUE THREAD

**Issue by static302** [zabbix-tooling/zabbix-ldap-sync#38]
Subject.
May be for some reason, but in this case option "--lowercase" is obsolete and confusing.
In fact all usernames synced from ldap are lowercased, which leads to a problems when doing some automation utilizing some third party tools matching real ldap sAMAccountName with usernames (aliases) in zabbix.
If it's done as it done just because lack of time - may be it will be better to leave usernames "as is" by default?

**Comment by scoopex** [comment]
Oh i am sorry. Seems to be overseen by the several refactorings.

With release 0.8 you can disable the modification of ldap account ids by using the "--ldap-accountids" flag.
