### ISSUE TITLE
Debian packaging: new release expected soon?

### ISSUE THREAD

**Issue by st31ny** [zabbix-tooling/zabbix-ldap-sync#62]
I want to package zabbix-ldap-sync for Debian and noticed that the last release 0.13 has been in Feb. 2022. Is there a release expected soon to incorporate the bugfixes since then?

**Comment by scoopex** [comment]
Hi, that's great. Contributors and collaborators are very welcomed :-)

I created a release for you: https://github.com/zabbix-tooling/zabbix-ldap-sync/releases/tag/1.0
Probably is a good idea to add release management and packaging triggered by github actions.

**Comment by st31ny** [comment]
Awesome, thanks!
