### ISSUE TITLE
Doesn`t work with more than one media type

### ISSUE THREAD

**Issue by davidakm74** [zabbix-tooling/zabbix-ldap-sync#8]
Cant configure to work with more than one media type, could please anyone share config with working more than 1 medias to sync? (for ex.: Email and SMS). 
When I use: 

[media]
description = Email, SMS
active = 0
period = 1-7,00:00-24:00
severity = 63
onlycreate = false

I have the result when mobile phones properly inserted as Emails :(

**Comment by ofbeaton** [comment]
Fix is posted in #17, waiting on PR.

**Comment by scoopex** [comment]
As described, waiting for a pull request :-)

**Comment by scoopex** [comment]
solved

**Comment by ofbeaton** [comment]
To be clear, you'll need 2 configs, one config file for SMS, and another for Email. Then you run the import tool twice, once for each config. The new merged code makes sure that new media types are always appended/updated to the current list.
