### ISSUE TITLE
zabbix-ldap-sync : command not found 

### ISSUE THREAD

**Issue by yousifAlkha** [zabbix-tooling/zabbix-ldap-sync#9]
can't run the script with 
zabbix-ldap-sync -f /home/user/zabbix-ldap-sync-master/zabbix-ldap.conf 
get an error of zabbix-ldap-sync : command not found

**Comment by vrtareg** [comment]
First of all you should make it executable. 
Second in Linux systems if file is not in PATH variable list then you should add ./ in front of name to indicate that it is executed from current directory or use full path to it aka /something/bin/zabbix-ldap-sync like you did for configuration file.

**Comment by scoopex** [comment]
Correct. Improved the documentation.
